### ISSUE TITLE
ClassCastException?

### ISSUE THREAD

**Issue by buczke** [FER-OOP/Lectures#2]
https://github.com/FER-OOP/Lectures/blob/65915cb542e5ee907cc745607eca0e6a005e34dd/08_Generics/src/main/java/hr/fer/oop/generics/example2/PointMain.java#L27

Pardon profesore nije li tu greska jer getX trenutno vraca String( obzirom na parametrizirani konstruktor za sPoint) koji ne mozemo castati u Integer preko Objecta?
Hvala

**Comment by boris612** [comment]
Da, kao što piše u komentarima ispod.

Neka imamo npr. Point<String> p = new Point<>(...)

Interno, zbog načina kako Java implementira Generics, private T x se pretvara u private Object x, pa je i getX() referenca tipa Object (a objekt na kojeg ta referena pokazuje bit će konkretnog tipa po kojem je izvršena parametrizacija), ali zato kompajler doda downcast u (String) getX()
pa je tako 
    String s = p.getX();
zapravo 
  String s = (String) p.getX();
Na taj način nam kompajler daje tipsku sigurnost kod rada s genericsima usprkos tome što u Javinoj virutalnoj mašini genericsi kao takvi ne postoje.

Razlog zašto možemo napisati Object o = p.getX()
je zato što za svaku referencu možemo napraviti upcast u Object. Kad imamo referencu tipa Object, kompajler će nas pustiti da napravimo downcast u bilo što, ali onda postoji šansa da prilikom izvršavanja programa utvrdi da downcast nije bio ispravan i baci ClassCastException.

Tako nam je programski kod
 Integer i = (Integer)(Object)sPoint.getX();
zapravo 
 Integer i = (Integer)(Object)(String) sPoint.getX();
i puknut će prilikom izvršavanja, jer downcast iz Object u Integer nije moguć, jer objekt u stvarnosti nije Integer, već je bio String.

  // But you can force compiler to forget types:
        Integer i = (Integer)(Object)sPoint.getX();
        // so now the following line will compile, but
        // will never execute since the previous one will
        // throw an exception...
        System.out.println(i.intValue());

**Comment by buczke** [comment]
U redu hvala
